# This file was generated by SableCC (http://www.sablecc.org/).

import sys
from Asi.Grammar.Lexer import Lexer
from Asi.Grammar.Node import EOF

def main():
    if len(sys.argv) != 2:
        print("usage:")
        print("    python testlexer.py <filename>")
    else:
        f = open(sys.argv[1], "r")
        _lexer = Lexer(f)

        while 1:
            token = _lexer.next()
            print("Read token '" + token.__class__.__name__ + "'" + ", text = [" + token.get_text() + "] at [" + str(token.get_line()) + "," + str(token.get_pos()) + "]")
            if isinstance(token, EOF):
                break
        f.close()

if __name__ == '__main__':
    main()
