# This file was generated by SableCC (http://www.sablecc.org/).

import sys
from Asi.grammar.lexer import Lexer
from Asi.grammar.nodes import EOF

def main():
    if len(sys.argv) != 2:
        print "usage:"
        print "    python testlexer.py <filename>"
    else:
        f = file(sys.argv[1], "r")
        _lexer = Lexer(f)

        while 1:
            token = _lexer.next()
            print "Read token '" + token.__class__.__name__ + "'" + ", text = [" + token.getText() + "] at [" + str(token.getLine()) + "," + str(token.getPos()) + "]"
            if isinstance(token, EOF): 
                break
        f.close()

if __name__ == '__main__':
    main()            
