name: Integration Tests

on:
  pull_request: # Run on all pull requests
  push:
    branches:   # Run on any push to development or main
      - development
      - main

jobs:
  tests:
    runs-on: ubuntu-20.04 #See pre-installed software at https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
    steps:
    - uses: actions/checkout@v3 #Checkout the project from git
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - run: pip install tox -r requirements_test_runner.txt -r requirements_test.txt
    - name: Run Tests
      run: tox -e py310
  flake8:
    runs-on: ubuntu-20.04 #See pre-installed software at https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
    steps:
    - uses: actions/checkout@v3 #Checkout the project from git
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - run: pip install tox flake8
    - name: Run Tests
      run: tox -e flake8
